// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymgxdgfxmxdglkzmjigc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZ3hkZ2Z4bXhkZ2xrem1qaWdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTE4MTEsImV4cCI6MjA1MDAyNzgxMX0.9hTu6IoC_-CcDnIs1bi2E7djMRApBRwhEc9UY1U4wHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);